feed_layout: "Classic"
color_scheme: "Auto"
language: 'en-uk'

# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: 
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: feed.xml

collections:
  authors:
    output: true


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
      current: author
      cover: false
      class: 'author-template'
      label: Author